config/routes.rb
Ram::Application.routes.draw do
  resources :kotis

  get "education/index"

  get "education/show"

  get "education/edit"

  get "education/new"

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  

  resources :emps

end

app/models/education.rb
class Education < ActiveRecord::Base
  attr_accessible :course, :place
#belongs_to :koti
end

app/models/emp.rb
class Emp < ActiveRecord::Base
  attr_accessible :address, :branch, :name, :phneno
end

app/models/koti.rb
class Koti < ActiveRecord::Base
  attr_accessible :course, :place
# has_many :educations
has_many :emps,:through=>:educations
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/education_controller.rb
class EducationController < ApplicationController
  # GET /Edus.json
  def index
    @edus = Edu.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @edus }
    end
  end

  # GET /Edus/1
  # GET /Edus/1.json
  def show
    @edu = Edu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @edu }
    end
  end

  # GET /Edus/new
  # GET /Edus/new.json
  def new
    @edu = Edu.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @edu }
    end
  end

  # GET /Edus/1/edit
  def edit
    @edu = Edu.find(params[:id])
  end

  # POST /Edus
  # POST /Edus.json
  def create
    @edu = Edu.new(params[:Edu])

    respond_to do |format|
      if @edu.save
        format.html { redirect_to @edu, notice: 'Edu was successfully created.' }
        format.json { render json: @edu, status: :created, location: @edu }
      else
        format.html { render action: "new" }
        format.json { render json: @edu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /Edus/1
  # PUT /Edus/1.json
  def update
    @edu = Edu.find(params[:id])

    respond_to do |format|
      if @edu.update_attributes(params[:Edu])
        format.html { redirect_to @edu, notice: 'Edu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @edu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /Edus/1
  # DELETE /Edus/1.json
  def destroy
    @edu = Edu.find(params[:id])
    @edu.destroy

    respond_to do |format|
      format.html { redirect_to Edus_url }
      format.json { head :no_content }
    end
  end
end
end

app/controllers/emps_controller.rb
class EmpsController < ApplicationController
  # GET /emps
  # GET /emps.json
  def index
    @emps = Emp.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @emps }
    end
  end

  # GET /emps/1
  # GET /emps/1.json
  def show
    @emp = Emp.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @emp }
    end
  end

  # GET /emps/new
  # GET /emps/new.json
  def new
    @emp = Emp.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @emp }
    end
  end

  # GET /emps/1/edit
  def edit
    @emp = Emp.find(params[:id])
  end

  # POST /emps
  # POST /emps.json
  def create
    @emp = Emp.new(params[:emp])

    respond_to do |format|
      if @emp.save
        format.html { redirect_to @emp, notice: 'Emp was successfully created.' }
        format.json { render json: @emp, status: :created, location: @emp }
      else
        format.html { render action: "new" }
        format.json { render json: @emp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /emps/1
  # PUT /emps/1.json
  def update
    @emp = Emp.find(params[:id])

    respond_to do |format|
      if @emp.update_attributes(params[:emp])
        format.html { redirect_to @emp, notice: 'Emp was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @emp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emps/1
  # DELETE /emps/1.json
  def destroy
    @emp = Emp.find(params[:id])
    @emp.destroy

    respond_to do |format|
      format.html { redirect_to emps_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/kotis_controller.rb
class KotisController < ApplicationController
  # GET /kotis
  # GET /kotis.json
  def index
    @kotis = Koti.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kotis }
    end
  end

  # GET /kotis/1
  # GET /kotis/1.json
  def show
    @koti = Koti.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @koti }
    end
  end

  # GET /kotis/new
  # GET /kotis/new.json
  def new
    @koti = Koti.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @koti }
    end
  end

  # GET /kotis/1/edit
  def edit
    @koti = Koti.find(params[:id])
  end

  # POST /kotis
  # POST /kotis.json
  def create
    @koti = Koti.new(params[:koti])

    respond_to do |format|
      if @koti.save
        format.html { redirect_to @koti, notice: 'Koti was successfully created.' }
        format.json { render json: @koti, status: :created, location: @koti }
      else
        format.html { render action: "new" }
        format.json { render json: @koti.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /kotis/1
  # PUT /kotis/1.json
  def update
    @koti = Koti.find(params[:id])

    respond_to do |format|
      if @koti.update_attributes(params[:koti])
        format.html { redirect_to @koti, notice: 'Koti was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @koti.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kotis/1
  # DELETE /kotis/1.json
  def destroy
    @koti = Koti.find(params[:id])
    @koti.destroy

    respond_to do |format|
      format.html { redirect_to kotis_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/education_helper.rb
module EducationHelper
end

app/helpers/emps_helper.rb
module EmpsHelper
end

app/helpers/kotis_helper.rb
module KotisHelper
end

app/views/education/_form.html.erb
<%= form_for(@edu) do |f| %>
  <% if @edu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@edu.errors.count, "error") %> prohibited this emp from being saved:</h2>

      <ul>
      <% @edu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course %><br />
    <%= f.text_field :course %>
  </div>
  <div class="field">
    <%= f.label :place %><br />
    <%= f.text_field :place %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/education/edit.html.erb
<h1>Editing emp</h1>

<%= render 'form' %>

<%= link_to 'Show', @du %> |
<%= link_to 'Back', edus_path %>

app/views/education/index.html.erb
<h1>Listing educations</h1>

<table>
  <tr>
    <th>course</th>
    <th>place</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @edus.each do |edu| %>
  <tr>
    <td><%= edu.course %></td>
    <td><%= edu.place %></td>
   
    <td><%= link_to 'Show', edu %></td>
    <td><%= link_to 'Edit', edit_edu_path(edu) %></td>
    <td><%= link_to 'Destroy', edu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New edu', new_edu_path %>

app/views/education/new.html.erb
<h1>New emp</h1>

<%= render 'form' %>

<%= link_to 'Back', edus_path %>

app/views/education/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Course:</b>
  <%= @edu.course %>
</p>

<p>
  <b>Branch:</b>
  <%= @edu.place %>
</p>


<%= link_to 'Edit', edit_edu_path(@edu) %> |
<%= link_to 'Back', edus_path %>

app/views/emps/_form.html.erb
<%= form_for(@emp) do |f| %>
  <% if @emp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@emp.errors.count, "error") %> prohibited this emp from being saved:</h2>

      <ul>
      <% @emp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :branch %><br />
    <%= f.text_field :branch %>
  </div>
  <div class="field">
    <%= f.label :phneno %><br />
    <%= f.text_field :phneno %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/emps/edit.html.erb
<h1>Editing emp</h1>

<%= render 'form' %>

<%= link_to 'Show', @emp %> |
<%= link_to 'Back', emps_path %>

app/views/emps/index.html.erb
<h1>Listing emps</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Branch</th>
    <th>Phneno</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @emps.each do |emp| %>
  <tr>
    <td><%= emp.name %></td>
    <td><%= emp.branch %></td>
    <td><%= emp.phneno %></td>
    <td><%= emp.address %></td>
    <td><%= link_to 'Show', emp %></td>
    <td><%= link_to 'Edit', edit_emp_path(emp) %></td>
    <td><%= link_to 'Destroy', emp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Emp', new_emp_path %>

app/views/emps/new.html.erb
<h1>New emp</h1>

<%= render 'form' %>

<%= link_to 'Back', emps_path %>

app/views/emps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @emp.name %>
</p>

<p>
  <b>Branch:</b>
  <%= @emp.branch %>
</p>

<p>
  <b>Phneno:</b>
  <%= @emp.phneno %>
</p>

<p>
  <b>Address:</b>
  <%= @emp.address %>
</p>


<%= link_to 'Edit', edit_emp_path(@emp) %> |
<%= link_to 'Back', emps_path %>

app/views/kotis/_form.html.erb
<%= form_for(@koti) do |f| %>
  <% if @koti.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@koti.errors.count, "error") %> prohibited this koti from being saved:</h2>

      <ul>
      <% @koti.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :place %><br />
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :course %><br />
    <%= f.text_field :course %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kotis/edit.html.erb
<h1>Editing koti</h1>

<%= render 'form' %>

<%= link_to 'Show', @koti %> |
<%= link_to 'Back', kotis_path %>

app/views/kotis/index.html.erb
<h1>Listing kotis</h1>

<table>
  <tr>
    <th>Place</th>
    <th>Course</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @kotis.each do |koti| %>
  <tr>
    <td><%= koti.place %></td>
    <td><%= koti.course %></td>
    <td><%= link_to 'Show', koti %></td>
    <td><%= link_to 'Edit', edit_koti_path(koti) %></td>
    <td><%= link_to 'Destroy', koti, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Koti', new_koti_path %>

app/views/kotis/new.html.erb
<h1>New koti</h1>

<%= render 'form' %>

<%= link_to 'Back', kotis_path %>

app/views/kotis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Place:</b>
  <%= @koti.place %>
</p>

<p>
  <b>Course:</b>
  <%= @koti.course %>
</p>


<%= link_to 'Edit', edit_koti_path(@koti) %> |
<%= link_to 'Back', kotis_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ram</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>